import { useEffect, useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { Link } from "react-router-dom";
import { X, Check, ShoppingBag, Plus, Minus, LoaderCircle, ShieldCheck, PackageCheck, ArrowRight } from "lucide-react";
import { fmtIDR } from "../lib/api";
import { variantLabel, variantsFor } from "../lib/catalog";

export default function StoreProductDialog({ open, product, products, loading, theme, adding, onSelect, onAdd, onClose, error }) {
  const minimum = Math.max(1, Number(product?.minimum_purchase_qty || 1));
  const maximum = Math.min(100, product?.stock == null ? 100 : Number(product.stock));
  const [quantity, setQuantity] = useState(minimum);
  useEffect(() => setQuantity(minimum), [product?._id, minimum]);
  const unavailable = !product || maximum < minimum;
  const price = Number(product?.price_idr_current ?? product?.price_idr ?? 0);
  const variants = product ? variantsFor(products, product) : [];
  const selectWithKeyboard = (event, index) => {
    const delta = ["ArrowRight", "ArrowDown"].includes(event.key) ? 1 : ["ArrowLeft", "ArrowUp"].includes(event.key) ? -1 : 0;
    if (!delta) return;
    event.preventDefault();
    const next = variants[(index + delta + variants.length) % variants.length];
    onSelect(next);
    event.currentTarget.parentElement.querySelector(`[data-variant-id="${CSS.escape(next._id)}"]`)?.focus();
  };
  return <Dialog.Root open={open} onOpenChange={(value) => { if (!value) onClose(); }}><Dialog.Portal>
    <Dialog.Overlay className="fixed inset-0 z-50 bg-slate-950/55 backdrop-blur-md data-[state=open]:animate-in data-[state=open]:fade-in"/>
    <Dialog.Content data-theme={theme} className="storefront-theme product-dialog fixed left-1/2 top-1/2 z-[60] max-h-[92dvh] w-[calc(100%-24px)] max-w-5xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-3xl border border-slate-200 bg-white text-slate-900 shadow-2xl outline-none sm:w-[calc(100%-48px)]">
      <Dialog.Close aria-label="Tutup detail produk" className="absolute right-3 top-3 z-10 rounded-full border border-slate-200 bg-white p-2.5 text-slate-600 hover:bg-slate-100 focus-visible:ring-2 focus-visible:ring-emerald-600"><X size={20}/></Dialog.Close>
      {!product ? <div className="p-10"><Dialog.Title className="text-xl font-bold">{loading ? "Memuat detail produk…" : "Produk tidak tersedia"}</Dialog.Title><Dialog.Description className="mt-3 text-slate-500">{loading ? "Menyiapkan pilihan varian dan harga terbaru." : "Produk ini mungkin sudah dinonaktifkan. Pilih produk lain melalui katalog."}</Dialog.Description><button className="mt-5 font-semibold text-emerald-800" onClick={onClose}>Kembali ke katalog</button></div> : <div className="grid md:grid-cols-[.9fr_1.1fr]">
        <div className="bg-slate-50 p-5 pt-14 sm:p-8 md:sticky md:top-0 md:h-fit"><div className="relative mx-auto aspect-square w-full max-w-[310px] overflow-hidden rounded-2xl border border-slate-200 bg-white sm:max-w-md"><img src={product.image_url || "/idse-logo.svg"} alt={product.name} className="h-full w-full object-contain" onError={(e) => { e.currentTarget.onerror = null; e.currentTarget.src = "/idse-logo.svg"; }}/></div><div className="mt-5 hidden gap-3 text-xs text-slate-600 md:grid"><span className="flex items-center gap-2"><ShieldCheck size={17} className="text-emerald-800"/> Bayar dengan QRIS atau saldo akun</span><span className="flex items-center gap-2"><PackageCheck size={17} className="text-emerald-800"/> Pantau pengiriman di menu Pesanan</span></div></div>
        <div className="p-5 sm:p-8 md:pt-12"><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-800">{product.catalog_name}</p><Dialog.Title className="mt-2 pr-4 text-2xl font-bold tracking-tight sm:text-3xl">{product.name}</Dialog.Title><Dialog.Description className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{product.description || "Pilih varian yang sesuai, periksa jumlah dan harga, lalu tambahkan ke keranjang."}</Dialog.Description>
          <div className="mt-5 flex flex-wrap items-end justify-between gap-3 rounded-2xl bg-emerald-50 p-4"><div><p className="text-xs text-slate-500">Harga per unit</p><p className="mt-1 text-2xl font-bold text-emerald-900">{fmtIDR(price)}</p>{Number(product.price_idr) > price && <p className="mt-1 text-xs text-slate-500 line-through">{fmtIDR(product.price_idr)}</p>}</div><span className={`rounded-full bg-white px-3 py-1.5 text-xs font-semibold ${unavailable ? "text-rose-700" : "text-emerald-800"}`}>{unavailable ? "Stok belum tersedia" : product.stock == null ? "Tersedia" : `${product.stock} tersedia`}</span></div>
          <fieldset className="mt-6"><legend className="font-semibold">Pilih varian <span className="ml-1 text-sm font-normal text-slate-500">({variants.length} pilihan)</span></legend><div role="radiogroup" aria-label="Varian produk" className="mt-3 grid max-h-64 gap-2 overflow-y-auto sm:grid-cols-2">{variants.map((variant, index) => { const selected = variant._id === product._id; const empty = variant.stock != null && Number(variant.stock) < Math.max(1, Number(variant.minimum_purchase_qty || 1)); return <button key={variant._id} type="button" role="radio" aria-checked={selected} tabIndex={selected ? 0 : -1} data-variant-id={variant._id} onKeyDown={(event) => selectWithKeyboard(event, index)} onClick={() => onSelect(variant)} className={`relative rounded-xl border p-3 text-left transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-600 ${selected ? "border-emerald-700 bg-emerald-50" : "border-slate-200 bg-white hover:border-emerald-500"}`}><span className="block pr-5 text-sm font-semibold">{variantLabel(variant)}</span><span className="mt-1 block text-xs text-slate-500">{fmtIDR(variant.price_idr_current ?? variant.price_idr)}{empty ? " · Habis" : " / unit"}</span>{selected && <Check size={15} className="absolute right-3 top-3 text-emerald-800"/>}</button>; })}</div></fieldset>
          <div className="mt-6 flex flex-wrap items-center justify-between gap-3"><div><label htmlFor="product-quantity" className="text-sm font-semibold">Jumlah</label><p className="mt-1 text-xs text-slate-500">Minimum {minimum} unit</p></div><div className="flex items-center rounded-xl border border-slate-200 p-1"><button aria-label="Kurangi jumlah varian" disabled={quantity <= minimum || adding || unavailable} onClick={() => setQuantity(Math.max(minimum, quantity-1))} className="rounded-lg p-2 disabled:opacity-30"><Minus size={17}/></button><input id="product-quantity" type="number" min={minimum} max={maximum} value={quantity} disabled={adding || unavailable} onChange={(e) => setQuantity(Math.min(maximum, Math.max(minimum, Number(e.target.value) || minimum)))} className="w-14 border-0 bg-transparent text-center text-sm font-bold outline-none"/><button aria-label="Tambah jumlah varian" disabled={quantity >= maximum || adding || unavailable} onClick={() => setQuantity(Math.min(maximum, quantity+1))} className="rounded-lg p-2 disabled:opacity-30"><Plus size={17}/></button></div></div>
          <div className="mt-5 flex justify-between border-t border-slate-200 pt-4 text-sm"><span className="text-slate-500">Subtotal pilihan</span><b>{fmtIDR(price * quantity)}</b></div><p className="mt-1 text-xs text-slate-500">Diskon jumlah dan kupon dihitung ulang di keranjang.</p>
          {error && <p role="alert" className="mt-3 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<button disabled={unavailable || adding} onClick={() => onAdd(product, quantity)} aria-busy={adding} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-800 px-4 py-3.5 font-semibold text-white transition hover:bg-emerald-900 disabled:opacity-45">{adding ? <LoaderCircle size={18} className="animate-spin"/> : <ShoppingBag size={18}/>} {adding ? "Menambahkan ke keranjang…" : "Tambah ke keranjang"}</button><Link to="/store/cart" className="mt-3 flex items-center justify-center gap-2 py-2 text-sm font-semibold text-emerald-800">Lihat keranjang <ArrowRight size={16}/></Link>
        </div>
      </div>}
    </Dialog.Content>
  </Dialog.Portal></Dialog.Root>;
}
