import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Pencil, CheckCircle2, LoaderCircle, Wallet, ShieldCheck, Send, LogOut, ClipboardList, RefreshCw } from "lucide-react";
import api, { fmtIDR, fmtUSD, formatApiErrorDetail } from "../lib/api";

const field = "mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-900 outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-600/20 disabled:bg-slate-50 disabled:text-slate-500";
export default function StoreProfile({ profile, onUpdate, onRefresh, onLogout, onLink, linkCode, botName, linkError }) {
  const [editing, setEditing] = useState(false);
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const originalName = profile?.display_name || profile?.first_name || "";
  useEffect(() => { setName(originalName); setPhone(profile?.phone || ""); }, [originalName, profile?.phone]);
  const cancel = () => { setName(originalName); setPhone(profile?.phone || ""); setEditing(false); setError(""); };
  const save = async (event) => {
    event.preventDefault(); setBusy(true); setError(""); setNotice("");
    try { const { data } = await api.patch("/store/me", { display_name: name.trim(), phone: phone.trim() }); onUpdate(data); setEditing(false); setNotice("Profil berhasil diperbarui."); }
    catch (e) { setError(formatApiErrorDetail(e.response?.data?.detail)); }
    finally { setBusy(false); }
  };
  if (!profile) return <div role="status" className="mx-auto max-w-5xl px-4 py-12 text-slate-500">Memuat profil…</div>;
  return <section className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold tracking-widest text-emerald-800">AKUN IDSE</p><h1 className="mt-2 text-3xl font-bold">Profil saya</h1><p className="mt-2 text-sm text-slate-500">Kelola identitas, saldo, dan akun yang terhubung.</p></div><Link to="/store/orders" className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold"><ClipboardList size={17}/> Pesanan saya</Link></div>
    <div className="mt-6 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><div className="space-y-5"><div className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><div className="flex items-center gap-4"><span className="grid h-16 w-16 shrink-0 place-items-center rounded-2xl bg-emerald-800 text-xl font-bold text-white">{String(originalName || profile.email || "ID").split(/\s+/).slice(0,2).map((v) => v[0]).join("").toUpperCase()}</span><div className="min-w-0"><h2 className="truncate text-lg font-bold">{originalName || "Lengkapi profilmu"}</h2><p className="mt-1 break-all text-sm text-slate-500">{profile.email}</p><span className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-emerald-800"><ShieldCheck size={13}/>{profile.email_verified ? "Email terverifikasi" : "Akun pelanggan"}</span></div></div>
      <div className="mt-6 flex items-center justify-between border-t border-slate-200 pt-5"><h3 className="font-semibold">Informasi pribadi</h3>{!editing && <button onClick={() => { setEditing(true); setNotice(""); }} className="inline-flex items-center gap-1.5 rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-800"><Pencil size={14}/> Edit profil</button>}</div><form onSubmit={save} className="mt-4 space-y-4"><label className="block text-sm font-medium">Nama tampilan<input className={field} value={name} onChange={(e) => setName(e.target.value)} required maxLength={80} disabled={!editing || busy} autoComplete="name" placeholder="Nama yang ingin ditampilkan"/></label><label className="block text-sm font-medium">Nomor kontak <span className="font-normal text-slate-500">(opsional)</span><input type="tel" className={field} value={phone} onChange={(e) => setPhone(e.target.value)} maxLength={30} disabled={!editing || busy} autoComplete="tel" placeholder="+62…"/></label><label className="block text-sm font-medium">Email login<input aria-label="Email login" aria-describedby="profile-email-help" className={field} value={profile.email || ""} readOnly disabled/><span id="profile-email-help" className="mt-2 block text-xs font-normal text-slate-500">Email terverifikasi digunakan untuk masuk dan menerima pesanan.</span></label>{error && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{notice && <p role="status" className="flex items-center gap-2 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800"><CheckCircle2 size={17}/>{notice}</p>}{editing && <div className="flex gap-3 pt-2"><button disabled={busy || !name.trim()} className="inline-flex items-center gap-2 rounded-xl bg-emerald-800 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy && <LoaderCircle size={16} className="animate-spin"/>}{busy ? "Menyimpan…" : "Simpan profil"}</button><button type="button" disabled={busy} onClick={cancel} className="rounded-xl border border-slate-200 px-5 py-3 text-sm font-semibold">Batal</button></div>}</form>
    </div><div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white p-5"><div><h3 className="text-sm font-semibold">Keamanan akun</h3><p className="mt-1 text-xs text-slate-500">Gunakan reset kata sandi pada halaman masuk bila diperlukan.</p></div><button onClick={onLogout} className="inline-flex items-center gap-2 rounded-xl bg-rose-50 px-4 py-2.5 text-sm font-semibold text-rose-700"><LogOut size={16}/> Keluar</button></div></div>
    <aside className="space-y-5"><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 sm:p-6"><div className="flex items-center gap-2 text-sm font-semibold text-emerald-800"><Wallet size={18}/> Saldo akun</div><p className="mt-4 text-3xl font-bold text-emerald-900">{fmtIDR(profile.balance_idr)}</p><p className="mt-2 text-sm text-slate-500">Saldo USD: {fmtUSD(profile.balance_usd)}</p><p className="mt-3 text-xs leading-5 text-slate-500">{profile.telegram_linked ? "Saldo terhubung dengan akun Telegram Anda." : "Gunakan saldo ini untuk checkout langsung."}</p><Link to="/store/deposit" className="mt-5 block rounded-xl bg-emerald-800 p-3 text-center text-sm font-semibold text-white">Tambah saldo</Link></div>
      <div className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center justify-between gap-2"><h3 className="flex items-center gap-2 font-semibold"><Send size={18} className="text-emerald-800"/> Telegram</h3><span className="rounded-full bg-slate-50 px-2.5 py-1 text-[10px] font-semibold text-slate-600">{profile.telegram_linked ? "Terhubung" : "Opsional"}</span></div><p className="mt-3 text-sm text-slate-600">{profile.telegram_linked ? profile.username ? `@${profile.username}` : `ID ${profile.telegram_id}` : "Hubungkan akun untuk memakai saldo yang sama di bot dan website."}</p>{!profile.telegram_linked && <><p className="mt-2 text-xs leading-5 text-slate-500">Saldo web dipindahkan satu kali saat penautan. Anda tetap dapat berbelanja tanpa Telegram.</p><button onClick={onLink} className="mt-4 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm font-semibold">Buat kode penghubung</button>{linkCode && <div className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><p>Kirim perintah ini ke {botName ? <a href={`https://t.me/${botName}`} target="_blank" rel="noreferrer" className="font-semibold text-emerald-800">@{botName}</a> : "bot IDSE"}:</p><code className="my-2 block select-all break-all font-bold">/link {linkCode}</code><p className="text-xs text-slate-500">Berlaku 10 menit.</p></div>}</>}{linkError && <p role="alert" className="mt-3 text-xs text-rose-700">{linkError}</p>}<button onClick={() => onRefresh().catch(() => setError("Profil belum dapat diperbarui."))} className="mt-4 inline-flex items-center gap-1.5 text-xs font-semibold text-emerald-800"><RefreshCw size={13}/> Perbarui status</button></div>
    </aside></div>
  </section>;
}
