import { Link, useNavigate } from "react-router-dom";
import { ArrowRight, Search, ShieldCheck, PackageCheck, CreditCard, Layers3, Sparkles, Check, Headset } from "lucide-react";
import { fmtIDR } from "../lib/api";
import { groupCatalogs, catalogHref, variantLabel } from "../lib/catalog";

export default function StoreHome({ products, loading, error, search, setSearch, onOpen, renderCatalog, renderProduct }) {
  const navigate = useNavigate();
  const catalogs = groupCatalogs(products);
  const ready = products.filter((p) => p.stock == null || p.stock >= Math.max(1, Number(p.minimum_purchase_qty || 1)));
  const featured = [...ready].sort((a,b) => Number(b.sales_count || 0) - Number(a.sales_count || 0)).slice(0, 3);
  const recommendations = [...ready].sort((a,b) => Number(b.discount_idr || 0) - Number(a.discount_idr || 0) || Number(b.sales_count || 0) - Number(a.sales_count || 0)).slice(0, 4);
  return <>
    <section className="store-hero relative overflow-hidden border-b border-slate-200"><div className="relative mx-auto grid max-w-7xl gap-8 px-4 py-8 sm:px-6 sm:py-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8"><div><span className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white px-3 py-1.5 text-[11px] font-semibold text-emerald-800"><Sparkles size={13}/> Pilihan digital untuk keseharianmu</span><h1 className="mt-5 max-w-xl text-4xl font-bold leading-[1.12] tracking-tight text-slate-950 sm:text-5xl lg:text-[56px]">Upgrade harimu.<br/><span className="text-emerald-800">Mulai dari sini.</span></h1><p className="mt-4 max-w-lg text-sm leading-7 text-slate-600 sm:text-base">Temukan layanan favorit, bandingkan durasinya, dan pilih yang paling pas. Satu tempat untuk kebutuhan digitalmu.</p>
      <form className="mt-6 flex max-w-lg gap-2 rounded-2xl border border-slate-200 bg-white p-2 shadow-sm" onSubmit={(event) => { event.preventDefault(); navigate(`/store/products?q=${encodeURIComponent(search.trim())}`); }}><label className="flex min-w-0 flex-1 items-center gap-2 pl-2"><Search size={19} className="shrink-0 text-slate-400"/><input aria-label="Cari produk dari beranda" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Cari Claude, ChatGPT, atau layanan…" className="w-full min-w-0 border-0 bg-transparent py-2 text-sm text-slate-900 outline-none"/></label><button aria-label="Cari produk" className="rounded-xl bg-emerald-800 px-4 py-3 text-sm font-semibold text-white hover:bg-emerald-900"><ArrowRight size={20}/></button></form>
      <div className="mt-4 flex flex-wrap items-center gap-2 text-xs"><span className="text-slate-500">Jelajahi:</span>{catalogs.slice(0, 3).map((catalog) => <Link key={catalog.key} to={catalogHref(catalog.name)} className="rounded-full border border-slate-200 bg-white/80 px-3 py-1.5 font-medium text-slate-700 hover:border-emerald-500">{catalog.name}</Link>)}</div>
      <div className="mt-7 flex flex-wrap gap-5 text-xs text-slate-600"><span className="flex items-center gap-1.5"><Layers3 size={15} className="text-emerald-800"/>{catalogs.length} katalog</span><span className="flex items-center gap-1.5"><PackageCheck size={15} className="text-emerald-800"/>{ready.length} pilihan tersedia</span><span className="flex items-center gap-1.5"><CreditCard size={15} className="text-emerald-800"/>QRIS & saldo</span></div></div>
      <div className="store-hero-shelf rounded-3xl border border-emerald-200 bg-white/80 p-4 shadow-sm sm:p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-emerald-800">Temukan pilihanmu</p><h2 className="mt-1 text-lg font-bold text-slate-900">Siap untuk upgrade?</h2></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-semibold text-emerald-800">Stok terkini</span></div>{featured.length ? <div className="space-y-3">{featured.map((product, index) => <button key={product._id} onClick={() => onOpen(product)} className="group flex w-full items-center gap-4 rounded-2xl border border-slate-200 bg-white p-3 text-left transition hover:-translate-y-0.5 hover:border-emerald-500 hover:shadow-md"><div className="h-20 w-20 shrink-0 overflow-hidden rounded-xl bg-slate-50 sm:h-24 sm:w-24"><img src={product.image_url || "/idse-logo.svg"} alt="" className="h-full w-full object-contain"/></div><span className="min-w-0 flex-1"><span className="text-[10px] font-semibold uppercase tracking-wider text-slate-500">{product.catalog_name}</span><span className="mt-1 block line-clamp-2 text-sm font-semibold text-slate-900">{product.name}</span><span className="mt-2 block text-sm font-bold text-emerald-800">{fmtIDR(product.price_idr_current ?? product.price_idr)}</span></span><span className="rounded-full bg-emerald-50 p-2 text-emerald-800"><ArrowRight size={17}/></span></button>)}</div> : <div className="rounded-2xl bg-slate-50 p-8 text-center text-sm text-slate-500">{loading ? "Memuat pilihan terbaru…" : "Produk tersedia akan tampil di sini."}</div>}<Link to="/store/products" className="mt-4 flex items-center justify-center gap-2 py-1 text-xs font-semibold text-emerald-800">Jelajahi semua katalog <ArrowRight size={15}/></Link></div>
    </div></section>
    <div className="border-b border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-4 px-4 py-5 sm:grid-cols-3 sm:px-6 lg:px-8">{[[ShieldCheck,"Pembayaran terverifikasi","QRIS langsung atau saldo akun"],[PackageCheck,"Detail pesanan tersimpan","Akses akun dan unduh dari riwayat"],[Headset,"Bantuan saat dibutuhkan","Hubungi admin melalui kontak toko"]].map(([Icon,title,text]) => <div key={title} className="flex items-center gap-3"><span className="rounded-xl bg-emerald-50 p-2.5 text-emerald-800"><Icon size={20}/></span><div><p className="text-xs font-semibold text-slate-900 sm:text-sm">{title}</p><p className="mt-0.5 text-xs text-slate-500">{text}</p></div></div>)}</div></div>
    <section className="mx-auto max-w-7xl px-4 py-9 sm:px-6 lg:px-8"><div className="mb-5 flex items-end justify-between gap-3"><div><p className="text-xs font-semibold text-emerald-800">MULAI DARI LAYANAN FAVORIT</p><h2 className="mt-2 text-2xl font-bold tracking-tight">Jelajahi katalog</h2></div><Link to="/store/products" className="flex items-center gap-1 text-xs font-semibold text-emerald-800 sm:text-sm">Semua katalog <ArrowRight size={16}/></Link></div>{error && <p role="alert" className="mb-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}{loading ? <div role="status" className="grid grid-cols-2 gap-4 sm:grid-cols-3">{[1,2,3].map((key) => <div key={key} className="h-60 animate-pulse rounded-2xl bg-slate-100"/>)}<span className="sr-only">Memuat katalog</span></div> : <div className="grid grid-cols-2 gap-3 sm:gap-4 lg:grid-cols-3">{catalogs.slice(0,6).map(renderCatalog)}</div>}{!loading && !catalogs.length && <p className="rounded-2xl border border-slate-200 bg-white p-8 text-center text-slate-500">Katalog sedang disiapkan. Silakan kembali beberapa saat lagi.</p>}</section>
    {recommendations.length > 0 && <section className="mx-auto max-w-7xl px-4 pb-10 sm:px-6 lg:px-8"><div className="mb-5 flex items-end justify-between gap-3"><div><p className="text-xs font-semibold text-emerald-800">PILIHAN YANG TERSEDIA</p><h2 className="mt-2 text-2xl font-bold tracking-tight">Temukan yang pas</h2></div><Link to="/store/products" className="text-xs font-semibold text-emerald-800">Lihat semua →</Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{recommendations.map(renderProduct)}</div></section>}
    <section className="mx-auto max-w-7xl px-4 pb-10 sm:px-6 lg:px-8"><div className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold text-emerald-800">BARU PERTAMA BELANJA?</p><h2 className="mt-2 text-xl font-bold">Tiga langkah, beres.</h2></div><Link to="/store/orders" className="text-sm font-semibold text-emerald-800">Cek pesanan saya →</Link></div><div className="mt-6 grid gap-5 sm:grid-cols-3">{[["01","Pilih varian","Buka katalog, bandingkan durasi dan harga."],["02","Selesaikan pembayaran","Periksa keranjang lalu bayar dengan QRIS atau saldo."],["03","Akses produkmu","Lihat status dan detail akun dari menu Pesanan."]].map(([number,title,text]) => <div key={number} className="flex gap-3"><span className="text-2xl font-bold text-emerald-800">{number}</span><div><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 text-xs leading-6 text-slate-500">{text}</p></div></div>)}</div></div></section>
  </>;
}
